---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec
  name: busser

platforms:
  - name: centos-7.3

suites:
#  - name: default
#    run_list:
#      - recipe[my-rails-app::default]
#    verifier:
#      inspec_tests:
#        - test/smoke/default
#      busser_tests:
#        - test/integration/default
#    attributes:
  - name: server
    run_list:
      - recipe[my-rails-app::server]
    verifier:
      inspec_tests:
        - test/smoke/default
      busser_tests:
        - test/integration/server
    attributes:

